on: push
jobs:
    Test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                CXX: ["g++", "clang++"]
                trace: ["-DJNIVM_ENABLE_TRACE=OFF", "-DJNIVM_ENABLE_TRACE=ON"]
                examples: ["-DJNIVM_BUILD_EXAMPLES=OFF", "-DJNIVM_BUILD_EXAMPLES=ON"]
        steps:
        - name: Checkout
          uses: actions/checkout@main
        - name: Configure
          env:
            CXX: ${{matrix.CXX}}
          run: |
            echo Configure with compiler $CXX
            mkdir build
            cd build
            cmake .. -DJNIVM_ENABLE_TESTS=ON -DJNIVM_ENABLE_RETURN_NON_ZERO=ON ${{matrix.trace}} ${{matrix.examples}}
        - name: Build
          run: |
            cd build
            cmake --build .
        - name: Run Tests
          run: |
            build/JNIVMTests
