on: push
jobs:
    Test:
        runs-on: Linux
        strategy:
            matrix:
                CXX: ["g++"]
        steps:
        - name: Checkout
          uses: actions/checkout@main
        - name: Configure
          env:
            CXX: ${{matrix.CXX}}
          run: |
            echo Configure with compiler $CXX
            mkdir build
            cd build
            cmake .. -DJNIVM_ENABLE_TESTS=ON -DJNIVM_BUILD_EXAMPLES=ON -DJNIVM_ENABLE_TRACE=ON
        - name: Build
          run: |
            cd build
            cmake --build .
        - name: Run Tests
          run: |
            build/JNIVMTests
